# Generated by Django 4.2.7 on 2025-12-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_customer_house_remove_customer_street_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='products/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logo Configuration',
                'verbose_name_plural': 'Logo Configuration',
            },
        ),
    ]
